@startuml "hub-request-processing"
!pragma layout smetana

!include ../../diagrams/diagram.styles.puml

hide empty description

state REQUESTED: <color:$darkGray>AssetRequestMessage
state AVAILABLE: <color:$darkGray>AssetAvailableMessage
state IN_PROGRESS: <color:$darkGray>TransferInProgressMessage
state COMPLETED: <color:$darkGray>TransferCompletedMessage

state ERROR $lightRed #$borderRed : <color:$darkGray>ErrorMessage
state CANCELLED $lightGray #$darkGray : <color:$darkGray>TransferCancelMessage

[*] --> REQUESTED: C
REQUESTED -->  AVAILABLE: P
REQUESTED -->  IN_PROGRESS: P
AVAILABLE -->  COMPLETED: C
IN_PROGRESS -->  COMPLETED: P
COMPLETED -->[*]
ERROR --> [*]
CANCELLED --> [*]

@enduml
