@startuml
!pragma layout smetana

!include ../../diagrams/diagram.styles.puml


abstract Policy {
}

hide circle

class Asset as "Asset Entry"{
}

class Agreement {
}


Policy <|-- Offer
Policy <|-- Agreement

CatalogService *-- Catalog
Catalog *-- Asset
Catalog *-- DataService
Connector <.. DataService
Asset *-- Offer

Agreement <-- Connector :  produces
Agreement ..> Asset

hide members

@enduml
           Cata
