@startuml "hub-request-processing"
!pragma layout smetana

!include ../diagrams/diagram.styles.puml

hide empty description

state CONSUMER_REQUESTED: <color:$darkGray>AssetRequestMessage
state READIED: <color:$darkGray>AssetReadyMessage
state STARTED: <color:$darkGray>TransferStartMessage
state COMPLETED: <color:$darkGray>TransferCompleteMessage
state SUSPENDED: <color:$darkGray>TransferSuspendMessage

state TERMINATED $lightRed #$borderRed : <color:$darkGray>TransferProcessTerminationMessage

[*] --> CONSUMER_REQUESTED: C
CONSUMER_REQUESTED -->  READIED: P
CONSUMER_REQUESTED -->  STARTED: P
READIED -->  COMPLETED: C
STARTED -->  COMPLETED: P
STARTED -->  SUSPENDED: P
READIED -->  SUSPENDED: P
SUSPENDED --> STARTED: P
SUSPENDED --> READIED: P
COMPLETED -->[*]

TERMINATED --> [*]

@enduml
