@startuml "hub-request-processing"
!pragma layout smetana

!include ../diagrams/diagram.styles.puml

hide empty description

state CONSUMER_REQUESTED: <color:$darkGray>AssetRequestMessage
state STARTED: <color:$darkGray>TransferProcessStartMessage
state COMPLETED: <color:$darkGray>TransferProcessCompletionMessage
state SUSPENDED: <color:$darkGray>TransferProcessSuspensionMessage

state TERMINATED $lightRed #$borderRed : <color:$darkGray>TransferProcessTerminationMessage

[*] --> CONSUMER_REQUESTED: C
CONSUMER_REQUESTED -->  STARTED: P
STARTED -->  COMPLETED: P/C
STARTED -->  SUSPENDED: P
SUSPENDED --> STARTED: P
COMPLETED -->[*]

TERMINATED --> [*]

@enduml
